/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as CalcRouteImport } from './routes/calc'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUUserSlugRouteImport } from './routes/_authenticated/u/$userSlug'
import { Route as AuthenticatedUUserSlugTeamsRouteImport } from './routes/_authenticated/u/$userSlug/teams'
import { Route as AuthenticatedUUserSlugTRouteImport } from './routes/_authenticated/u/$userSlug/t'
import { Route as AuthenticatedUUserSlugPokemonRouteImport } from './routes/_authenticated/u/$userSlug/pokemon'
import { Route as AuthenticatedUUserSlugTeamsIndexRouteImport } from './routes/_authenticated/u/$userSlug/teams/index'
import { Route as AuthenticatedUUserSlugTIndexRouteImport } from './routes/_authenticated/u/$userSlug/t/index'
import { Route as AuthenticatedUUserSlugPokemonIndexRouteImport } from './routes/_authenticated/u/$userSlug/pokemon/index'
import { Route as AuthenticatedUUserSlugTeamsTeamSlugRouteImport } from './routes/_authenticated/u/$userSlug/teams/$teamSlug'
import { Route as AuthenticatedUUserSlugTTeamSlugRouteImport } from './routes/_authenticated/u/$userSlug/t/$teamSlug'
import { Route as AuthenticatedUUserSlugPokemonNameSlugRouteImport } from './routes/_authenticated/u/$userSlug/pokemon/$nameSlug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcRoute = CalcRouteImport.update({
  id: '/calc',
  path: '/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUUserSlugRoute = AuthenticatedUUserSlugRouteImport.update({
  id: '/u/$userSlug',
  path: '/u/$userSlug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUUserSlugTeamsRoute =
  AuthenticatedUUserSlugTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedUUserSlugRoute,
  } as any)
const AuthenticatedUUserSlugTRoute = AuthenticatedUUserSlugTRouteImport.update({
  id: '/t',
  path: '/t',
  getParentRoute: () => AuthenticatedUUserSlugRoute,
} as any)
const AuthenticatedUUserSlugPokemonRoute =
  AuthenticatedUUserSlugPokemonRouteImport.update({
    id: '/pokemon',
    path: '/pokemon',
    getParentRoute: () => AuthenticatedUUserSlugRoute,
  } as any)
const AuthenticatedUUserSlugTeamsIndexRoute =
  AuthenticatedUUserSlugTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUUserSlugTeamsRoute,
  } as any)
const AuthenticatedUUserSlugTIndexRoute =
  AuthenticatedUUserSlugTIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUUserSlugTRoute,
  } as any)
const AuthenticatedUUserSlugPokemonIndexRoute =
  AuthenticatedUUserSlugPokemonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUUserSlugPokemonRoute,
  } as any)
const AuthenticatedUUserSlugTeamsTeamSlugRoute =
  AuthenticatedUUserSlugTeamsTeamSlugRouteImport.update({
    id: '/$teamSlug',
    path: '/$teamSlug',
    getParentRoute: () => AuthenticatedUUserSlugTeamsRoute,
  } as any)
const AuthenticatedUUserSlugTTeamSlugRoute =
  AuthenticatedUUserSlugTTeamSlugRouteImport.update({
    id: '/$teamSlug',
    path: '/$teamSlug',
    getParentRoute: () => AuthenticatedUUserSlugTRoute,
  } as any)
const AuthenticatedUUserSlugPokemonNameSlugRoute =
  AuthenticatedUUserSlugPokemonNameSlugRouteImport.update({
    id: '/$nameSlug',
    path: '/$nameSlug',
    getParentRoute: () => AuthenticatedUUserSlugPokemonRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calc': typeof CalcRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/u/$userSlug': typeof AuthenticatedUUserSlugRouteWithChildren
  '/u/$userSlug/pokemon': typeof AuthenticatedUUserSlugPokemonRouteWithChildren
  '/u/$userSlug/t': typeof AuthenticatedUUserSlugTRouteWithChildren
  '/u/$userSlug/teams': typeof AuthenticatedUUserSlugTeamsRouteWithChildren
  '/u/$userSlug/pokemon/$nameSlug': typeof AuthenticatedUUserSlugPokemonNameSlugRoute
  '/u/$userSlug/t/$teamSlug': typeof AuthenticatedUUserSlugTTeamSlugRoute
  '/u/$userSlug/teams/$teamSlug': typeof AuthenticatedUUserSlugTeamsTeamSlugRoute
  '/u/$userSlug/pokemon/': typeof AuthenticatedUUserSlugPokemonIndexRoute
  '/u/$userSlug/t/': typeof AuthenticatedUUserSlugTIndexRoute
  '/u/$userSlug/teams/': typeof AuthenticatedUUserSlugTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calc': typeof CalcRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/u/$userSlug': typeof AuthenticatedUUserSlugRouteWithChildren
  '/u/$userSlug/pokemon/$nameSlug': typeof AuthenticatedUUserSlugPokemonNameSlugRoute
  '/u/$userSlug/t/$teamSlug': typeof AuthenticatedUUserSlugTTeamSlugRoute
  '/u/$userSlug/teams/$teamSlug': typeof AuthenticatedUUserSlugTeamsTeamSlugRoute
  '/u/$userSlug/pokemon': typeof AuthenticatedUUserSlugPokemonIndexRoute
  '/u/$userSlug/t': typeof AuthenticatedUUserSlugTIndexRoute
  '/u/$userSlug/teams': typeof AuthenticatedUUserSlugTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/account': typeof AccountRoute
  '/calc': typeof CalcRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/u/$userSlug': typeof AuthenticatedUUserSlugRouteWithChildren
  '/_authenticated/u/$userSlug/pokemon': typeof AuthenticatedUUserSlugPokemonRouteWithChildren
  '/_authenticated/u/$userSlug/t': typeof AuthenticatedUUserSlugTRouteWithChildren
  '/_authenticated/u/$userSlug/teams': typeof AuthenticatedUUserSlugTeamsRouteWithChildren
  '/_authenticated/u/$userSlug/pokemon/$nameSlug': typeof AuthenticatedUUserSlugPokemonNameSlugRoute
  '/_authenticated/u/$userSlug/t/$teamSlug': typeof AuthenticatedUUserSlugTTeamSlugRoute
  '/_authenticated/u/$userSlug/teams/$teamSlug': typeof AuthenticatedUUserSlugTeamsTeamSlugRoute
  '/_authenticated/u/$userSlug/pokemon/': typeof AuthenticatedUUserSlugPokemonIndexRoute
  '/_authenticated/u/$userSlug/t/': typeof AuthenticatedUUserSlugTIndexRoute
  '/_authenticated/u/$userSlug/teams/': typeof AuthenticatedUUserSlugTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/calc'
    | '/sign-in'
    | '/sign-up'
    | '/u/$userSlug'
    | '/u/$userSlug/pokemon'
    | '/u/$userSlug/t'
    | '/u/$userSlug/teams'
    | '/u/$userSlug/pokemon/$nameSlug'
    | '/u/$userSlug/t/$teamSlug'
    | '/u/$userSlug/teams/$teamSlug'
    | '/u/$userSlug/pokemon/'
    | '/u/$userSlug/t/'
    | '/u/$userSlug/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/calc'
    | '/sign-in'
    | '/sign-up'
    | '/u/$userSlug'
    | '/u/$userSlug/pokemon/$nameSlug'
    | '/u/$userSlug/t/$teamSlug'
    | '/u/$userSlug/teams/$teamSlug'
    | '/u/$userSlug/pokemon'
    | '/u/$userSlug/t'
    | '/u/$userSlug/teams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/calc'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/u/$userSlug'
    | '/_authenticated/u/$userSlug/pokemon'
    | '/_authenticated/u/$userSlug/t'
    | '/_authenticated/u/$userSlug/teams'
    | '/_authenticated/u/$userSlug/pokemon/$nameSlug'
    | '/_authenticated/u/$userSlug/t/$teamSlug'
    | '/_authenticated/u/$userSlug/teams/$teamSlug'
    | '/_authenticated/u/$userSlug/pokemon/'
    | '/_authenticated/u/$userSlug/t/'
    | '/_authenticated/u/$userSlug/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountRoute: typeof AccountRoute
  CalcRoute: typeof CalcRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc': {
      id: '/calc'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$userSlug': {
      id: '/_authenticated/u/$userSlug'
      path: '/u/$userSlug'
      fullPath: '/u/$userSlug'
      preLoaderRoute: typeof AuthenticatedUUserSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$userSlug/teams': {
      id: '/_authenticated/u/$userSlug/teams'
      path: '/teams'
      fullPath: '/u/$userSlug/teams'
      preLoaderRoute: typeof AuthenticatedUUserSlugTeamsRouteImport
      parentRoute: typeof AuthenticatedUUserSlugRoute
    }
    '/_authenticated/u/$userSlug/t': {
      id: '/_authenticated/u/$userSlug/t'
      path: '/t'
      fullPath: '/u/$userSlug/t'
      preLoaderRoute: typeof AuthenticatedUUserSlugTRouteImport
      parentRoute: typeof AuthenticatedUUserSlugRoute
    }
    '/_authenticated/u/$userSlug/pokemon': {
      id: '/_authenticated/u/$userSlug/pokemon'
      path: '/pokemon'
      fullPath: '/u/$userSlug/pokemon'
      preLoaderRoute: typeof AuthenticatedUUserSlugPokemonRouteImport
      parentRoute: typeof AuthenticatedUUserSlugRoute
    }
    '/_authenticated/u/$userSlug/teams/': {
      id: '/_authenticated/u/$userSlug/teams/'
      path: '/'
      fullPath: '/u/$userSlug/teams/'
      preLoaderRoute: typeof AuthenticatedUUserSlugTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedUUserSlugTeamsRoute
    }
    '/_authenticated/u/$userSlug/t/': {
      id: '/_authenticated/u/$userSlug/t/'
      path: '/'
      fullPath: '/u/$userSlug/t/'
      preLoaderRoute: typeof AuthenticatedUUserSlugTIndexRouteImport
      parentRoute: typeof AuthenticatedUUserSlugTRoute
    }
    '/_authenticated/u/$userSlug/pokemon/': {
      id: '/_authenticated/u/$userSlug/pokemon/'
      path: '/'
      fullPath: '/u/$userSlug/pokemon/'
      preLoaderRoute: typeof AuthenticatedUUserSlugPokemonIndexRouteImport
      parentRoute: typeof AuthenticatedUUserSlugPokemonRoute
    }
    '/_authenticated/u/$userSlug/teams/$teamSlug': {
      id: '/_authenticated/u/$userSlug/teams/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/u/$userSlug/teams/$teamSlug'
      preLoaderRoute: typeof AuthenticatedUUserSlugTeamsTeamSlugRouteImport
      parentRoute: typeof AuthenticatedUUserSlugTeamsRoute
    }
    '/_authenticated/u/$userSlug/t/$teamSlug': {
      id: '/_authenticated/u/$userSlug/t/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/u/$userSlug/t/$teamSlug'
      preLoaderRoute: typeof AuthenticatedUUserSlugTTeamSlugRouteImport
      parentRoute: typeof AuthenticatedUUserSlugTRoute
    }
    '/_authenticated/u/$userSlug/pokemon/$nameSlug': {
      id: '/_authenticated/u/$userSlug/pokemon/$nameSlug'
      path: '/$nameSlug'
      fullPath: '/u/$userSlug/pokemon/$nameSlug'
      preLoaderRoute: typeof AuthenticatedUUserSlugPokemonNameSlugRouteImport
      parentRoute: typeof AuthenticatedUUserSlugPokemonRoute
    }
  }
}

interface AuthenticatedUUserSlugPokemonRouteChildren {
  AuthenticatedUUserSlugPokemonNameSlugRoute: typeof AuthenticatedUUserSlugPokemonNameSlugRoute
  AuthenticatedUUserSlugPokemonIndexRoute: typeof AuthenticatedUUserSlugPokemonIndexRoute
}

const AuthenticatedUUserSlugPokemonRouteChildren: AuthenticatedUUserSlugPokemonRouteChildren =
  {
    AuthenticatedUUserSlugPokemonNameSlugRoute:
      AuthenticatedUUserSlugPokemonNameSlugRoute,
    AuthenticatedUUserSlugPokemonIndexRoute:
      AuthenticatedUUserSlugPokemonIndexRoute,
  }

const AuthenticatedUUserSlugPokemonRouteWithChildren =
  AuthenticatedUUserSlugPokemonRoute._addFileChildren(
    AuthenticatedUUserSlugPokemonRouteChildren,
  )

interface AuthenticatedUUserSlugTRouteChildren {
  AuthenticatedUUserSlugTTeamSlugRoute: typeof AuthenticatedUUserSlugTTeamSlugRoute
  AuthenticatedUUserSlugTIndexRoute: typeof AuthenticatedUUserSlugTIndexRoute
}

const AuthenticatedUUserSlugTRouteChildren: AuthenticatedUUserSlugTRouteChildren =
  {
    AuthenticatedUUserSlugTTeamSlugRoute: AuthenticatedUUserSlugTTeamSlugRoute,
    AuthenticatedUUserSlugTIndexRoute: AuthenticatedUUserSlugTIndexRoute,
  }

const AuthenticatedUUserSlugTRouteWithChildren =
  AuthenticatedUUserSlugTRoute._addFileChildren(
    AuthenticatedUUserSlugTRouteChildren,
  )

interface AuthenticatedUUserSlugTeamsRouteChildren {
  AuthenticatedUUserSlugTeamsTeamSlugRoute: typeof AuthenticatedUUserSlugTeamsTeamSlugRoute
  AuthenticatedUUserSlugTeamsIndexRoute: typeof AuthenticatedUUserSlugTeamsIndexRoute
}

const AuthenticatedUUserSlugTeamsRouteChildren: AuthenticatedUUserSlugTeamsRouteChildren =
  {
    AuthenticatedUUserSlugTeamsTeamSlugRoute:
      AuthenticatedUUserSlugTeamsTeamSlugRoute,
    AuthenticatedUUserSlugTeamsIndexRoute:
      AuthenticatedUUserSlugTeamsIndexRoute,
  }

const AuthenticatedUUserSlugTeamsRouteWithChildren =
  AuthenticatedUUserSlugTeamsRoute._addFileChildren(
    AuthenticatedUUserSlugTeamsRouteChildren,
  )

interface AuthenticatedUUserSlugRouteChildren {
  AuthenticatedUUserSlugPokemonRoute: typeof AuthenticatedUUserSlugPokemonRouteWithChildren
  AuthenticatedUUserSlugTRoute: typeof AuthenticatedUUserSlugTRouteWithChildren
  AuthenticatedUUserSlugTeamsRoute: typeof AuthenticatedUUserSlugTeamsRouteWithChildren
}

const AuthenticatedUUserSlugRouteChildren: AuthenticatedUUserSlugRouteChildren =
  {
    AuthenticatedUUserSlugPokemonRoute:
      AuthenticatedUUserSlugPokemonRouteWithChildren,
    AuthenticatedUUserSlugTRoute: AuthenticatedUUserSlugTRouteWithChildren,
    AuthenticatedUUserSlugTeamsRoute:
      AuthenticatedUUserSlugTeamsRouteWithChildren,
  }

const AuthenticatedUUserSlugRouteWithChildren =
  AuthenticatedUUserSlugRoute._addFileChildren(
    AuthenticatedUUserSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedUUserSlugRoute: typeof AuthenticatedUUserSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUUserSlugRoute: AuthenticatedUUserSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountRoute: AccountRoute,
  CalcRoute: CalcRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
